SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `countries` (
  `id` int(10) NOT NULL,
  `iso2` char(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ISO 3166-1 alfa-2',
  `iso3` char(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ISO 3166-1 alfa-3',
  `is_eu` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'The country is a member of the European Union.',
  `eng` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'English',
  `spa` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Spanish',
  `cat` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Catalan'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Country';

INSERT INTO `countries` (`id`, `iso2`, `iso3`, `is_eu`, `eng`, `spa`, `cat`) VALUES
(1, 'AD', 'AND', 0, 'Andorra', 'Andorra', 'Andorra'),
(2, 'AE', 'ARE', 0, 'United Arab Emirates', 'Emiratos Árabes Unidos', 'Emirats Àrabs Units'),
(3, 'AF', 'AFG', 0, 'Afghanistan', 'Afganistán', 'Afganistan'),
(4, 'AG', 'ATG', 0, 'Antigua and Barbuda', 'Antigua y Barbuda', 'Antigua i Barbuda'),
(5, 'AI', 'AIA', 0, 'Anguilla', 'Anguilla', 'Anguilla'),
(6, 'AL', 'ALB', 0, 'Albania', 'Albania', 'Albània'),
(7, 'AM', 'ARM', 0, 'Armenia', 'Armenia', 'Armènia'),
(8, 'AO', 'AGO', 0, 'Angola', 'Angola', 'Angola'),
(9, 'AQ', 'ATA', 0, 'Antarctica', 'Antártida', 'Antàrtida'),
(10, 'AR', 'ARG', 0, 'Argentina', 'Argentina', 'Argentina'),
(11, 'AS', 'ASM', 0, 'American Samoa', 'Samoa Americana', 'Samoa Nord-americana'),
(12, 'AT', 'AUT', 1, 'Austria', 'Austria', 'Àustria'),
(13, 'AU', 'AUS', 0, 'Australia', 'Australia', 'Austràlia'),
(14, 'AW', 'ABW', 0, 'Aruba', 'Aruba', 'Aruba'),
(15, 'AX', 'ALA', 0, 'Aland Islands', 'Islas Gland', 'Åland, illes'),
(16, 'AZ', 'AZE', 0, 'Azerbaijan', 'Azerbaiyán', 'Azerbaidjan'),
(17, 'BA', 'BIH', 0, 'Bosnia and Herzegovina', 'Bosnia y Herzegovina', 'Bòsnia i Hercegovina'),
(18, 'BB', 'BRB', 0, 'Barbados', 'Barbados', 'Barbados'),
(19, 'BD', 'BGD', 0, 'Bangladesh', 'Bangladesh', 'Bangla Desh'),
(20, 'BE', 'BEL', 1, 'Belgium', 'Bélgica', 'Bèlgica'),
(21, 'BF', 'BFA', 0, 'Burkina Faso', 'Burkina Faso', 'Burkina Faso'),
(22, 'BG', 'BGR', 1, 'Bulgaria', 'Bulgaria', 'Bulgària'),
(23, 'BH', 'BHR', 0, 'Bahrain', 'Bahréin', 'Bahrain'),
(24, 'BI', 'BDI', 0, 'Burundi', 'Burundi', 'Burundi'),
(25, 'BJ', 'BEN', 0, 'Benin', 'Benin', 'Benín'),
(26, 'BL', 'BLM', 0, 'Saint Bartelemey', 'San Bartolomé', 'Saint-Barthélemy'),
(27, 'BM', 'BMU', 0, 'Bermuda', 'Bermudas', 'Bermudes'),
(28, 'BN', 'BRN', 0, 'Brunei Darussalam', 'Brunéi', 'Brunei'),
(29, 'BO', 'BOL', 0, 'Bolivia', 'Bolivia', 'Bolívia'),
(30, 'BQ', 'ATB', 0, 'Bonaire, Saint Eustatius and Saba', 'Bonaire, Saint Eustatius y Saba', 'Bonaire, Saint Eustatius i Saba'),
(31, 'BR', 'BRA', 0, 'Brazil', 'Brasil', 'Brasil'),
(32, 'BS', 'BHS', 0, 'Bahamas', 'Bahamas', 'Bahames'),
(33, 'BT', 'BTN', 0, 'Bhutan', 'Bhután', 'Bhutan'),
(34, 'BV', 'BVT', 0, 'Bouvet Island', 'Isla Bouvet', 'Bouvet'),
(35, 'BW', 'BWA', 0, 'Botswana', 'Botsuana', 'Botswana'),
(36, 'BY', 'BLR', 0, 'Belarus', 'Bielorrusia', 'Bielorússia'),
(37, 'BZ', 'BLZ', 0, 'Belize', 'Belice', 'Belize'),
(38, 'CA', 'CAN', 0, 'Canada', 'Canadá', 'Canadà'),
(39, 'CC', 'CCK', 0, 'Cocos (Keeling) Islands', 'Islas Cocos', 'Cocos, illes'),
(40, 'CD', 'COD', 0, 'Congo, The Democratic Republic of the', 'República Democrática del Congo', 'Congo, República Democràtica del'),
(41, 'CF', 'CAF', 0, 'Central African Republic', 'República Centroafricana', 'Centreafricana, República'),
(42, 'CG', 'COG', 0, 'Congo', 'Congo', 'Congo, República del'),
(43, 'CH', 'CHE', 0, 'Switzerland', 'Suiza', 'Suïssa'),
(44, 'CI', 'CIV', 0, 'Cote d\'Ivoire', 'Costa de Marfil', 'Costa d\'Ivori'),
(45, 'CK', 'COK', 0, 'Cook Islands', 'Islas Cook', 'Cook, illes'),
(46, 'CL', 'CHL', 0, 'Chile', 'Chile', 'Xile'),
(47, 'CM', 'CMR', 0, 'Cameroon', 'Camerún', 'Camerun'),
(48, 'CN', 'CHN', 0, 'China', 'China', 'Xina'),
(49, 'CO', 'COL', 0, 'Colombia', 'Colombia', 'Colòmbia'),
(50, 'CR', 'CRI', 0, 'Costa Rica', 'Costa Rica', 'Costa Rica'),
(51, 'CU', 'CUB', 0, 'Cuba', 'Cuba', 'Cuba'),
(52, 'CV', 'CPV', 0, 'Cape Verde', 'Cabo Verde', 'Cap Verd'),
(53, 'CW', 'CUW', 0, 'Curacao', 'Curazao', 'Curaçao'),
(54, 'CX', 'CXR', 0, 'Christmas Island', 'Isla de Navidad', 'Christmas, illa'),
(55, 'CY', 'CYP', 1, 'Cyprus', 'Chipre', 'Xipre'),
(56, 'CZ', 'CZE', 1, 'Czech Republic', 'República Checa', 'Txeca, República'),
(57, 'DE', 'DEU', 1, 'Germany', 'Alemania', 'Alemanya'),
(58, 'DJ', 'DJI', 0, 'Djibouti', 'Yibuti', 'Djibouti'),
(59, 'DK', 'DNK', 1, 'Denmark', 'Dinamarca', 'Dinamarca'),
(60, 'DM', 'DMA', 0, 'Dominica', 'Dominica', 'Dominica'),
(61, 'DO', 'DOM', 0, 'Dominican Republic', 'República Dominicana', 'Dominicana, República'),
(62, 'DZ', 'DZA', 0, 'Algeria', 'Argelia', 'Algèria'),
(63, 'EC', 'ECU', 0, 'Ecuador', 'Ecuador', 'Equador'),
(64, 'EE', 'EST', 1, 'Estonia', 'Estonia', 'Estònia'),
(65, 'EG', 'EGY', 0, 'Egypt', 'Egipto', 'Egipte'),
(66, 'EH', 'ESH', 0, 'Western Sahara', 'Sahara Occidental', 'Sàhara Occidental'),
(67, 'ER', 'ERI', 0, 'Eritrea', 'Eritrea', 'Eritrea'),
(68, 'ES', 'ESP', 1, 'Spain', 'España', 'Espanya'),
(69, 'ET', 'ETH', 0, 'Ethiopia', 'Etiopía', 'Etiòpia'),
(70, 'FI', 'FIN', 1, 'Finland', 'Finlandia', 'Finlàndia'),
(71, 'FJ', 'FJI', 0, 'Fiji', 'Fiyi', 'Fiji'),
(72, 'FK', 'FLK', 0, 'Falkland Islands (Malvinas)', 'Islas Malvinas', 'Malvines, illes'),
(73, 'FM', 'FSM', 0, 'Micronesia, Federated States of', 'Micronesia', 'Micronèsia, Estats Federats de'),
(74, 'FO', 'FRO', 0, 'Faroe Islands', 'Islas Feroe', 'Fèroe, illes'),
(75, 'FR', 'FRA', 1, 'France', 'Francia', 'França'),
(76, 'GA', 'GAB', 0, 'Gabon', 'Gabón', 'Gabon'),
(77, 'GB', 'GBR', 1, 'United Kingdom', 'Reino Unido', 'Regne Unit'),
(78, 'GD', 'GRD', 0, 'Grenada', 'Granada', 'Grenada'),
(79, 'GE', 'GEO', 0, 'Georgia', 'Georgia', 'Geòrgia'),
(80, 'GF', 'GUF', 0, 'French Guiana', 'Guayana Francesa', 'Guaiana Francesa'),
(81, 'GG', 'GGY', 0, 'Guernsey', 'Guernsey', 'Guernsey'),
(82, 'GH', 'GHA', 0, 'Ghana', 'Ghana', 'Ghana'),
(83, 'GI', 'GIB', 0, 'Gibraltar', 'Gibraltar', 'Gibraltar'),
(84, 'GL', 'GRL', 0, 'Greenland', 'Groenlandia', 'Groenlàndia'),
(85, 'GM', 'GMB', 0, 'Gambia', 'Gambia', 'Gàmbia'),
(86, 'GN', 'GIN', 0, 'Guinea', 'Guinea', 'República de Guinea'),
(87, 'GP', 'GLP', 0, 'Guadeloupe', 'Guadalupe', 'Guadeloupe'),
(88, 'GQ', 'GNQ', 0, 'Equatorial Guinea', 'Guinea Ecuatorial', 'Guinea Equatorial'),
(89, 'GR', 'GRC', 1, 'Greece', 'Grecia', 'Grècia'),
(90, 'GS', 'SGS', 0, 'South Georgia and the South Sandwich Islands', 'Islas Georgias del Sur y Sandwich del Sur', 'Geòrgia del Sud i Sandwich del Sud, illes'),
(91, 'GT', 'GTM', 0, 'Guatemala', 'Guatemala', 'Guatemala'),
(92, 'GU', 'GUM', 0, 'Guam', 'Guam', 'Guam'),
(93, 'GW', 'GNB', 0, 'Guinea-Bissau', 'Guinea-Bissau', 'Guinea Bissau'),
(94, 'GY', 'GUY', 0, 'Guyana', 'Guyana', 'Guyana'),
(95, 'HK', 'HKG', 0, 'Hong Kong', 'Hong Kong', 'Hong Kong'),
(96, 'HM', 'HMD', 0, 'Heard Island and McDonald Islands', 'Islas Heard y McDonald', 'Heard, illa i McDonald, illes'),
(97, 'HN', 'HND', 0, 'Honduras', 'Honduras', 'Hondures'),
(98, 'HR', 'HRV', 1, 'Croatia', 'Croacia', 'Croàcia'),
(99, 'HT', 'HTI', 0, 'Haiti', 'Haití', 'Haití'),
(100, 'HU', 'HUN', 1, 'Hungary', 'Hungría', 'Hongria'),
(101, 'ID', 'IDN', 0, 'Indonesia', 'Indonesia', 'Indonèsia'),
(102, 'IE', 'IRL', 1, 'Ireland', 'Irlanda', 'Irlanda'),
(103, 'IL', 'ISR', 0, 'Israel', 'Israel', 'Israel'),
(104, 'IM', 'IMN', 0, 'Isle of Man', 'Isla de Man', 'Illa de Man'),
(105, 'IN', 'IND', 0, 'India', 'India', 'Índia'),
(106, 'IO', 'IOT', 0, 'British Indian Ocean Territory', 'Territorio Británico del Océano Índico', 'Territori Britànic de l\'Oceà Índic'),
(107, 'IQ', 'IRQ', 0, 'Iraq', 'Iraq', 'Iraq'),
(108, 'IR', 'IRN', 0, 'Iran, Islamic Republic of', 'Irán', 'Iran'),
(109, 'IS', 'ISL', 0, 'Iceland', 'Islandia', 'Islàndia'),
(110, 'IT', 'ITA', 1, 'Italy', 'Italia', 'Itàlia'),
(111, 'JE', 'JEY', 0, 'Jersey', 'Jersey', 'Jersey'),
(112, 'JM', 'JAM', 0, 'Jamaica', 'Jamaica', 'Jamaica'),
(113, 'JO', 'JOR', 0, 'Jordan', 'Jordania', 'Jordània'),
(114, 'JP', 'JPN', 0, 'Japan', 'Japón', 'Japó'),
(115, 'KE', 'KEN', 0, 'Kenya', 'Kenia', 'Kenya'),
(116, 'KG', 'KGZ', 0, 'Kyrgyzstan', 'Kirguistán', 'Kirguizistan'),
(117, 'KH', 'KHM', 0, 'Cambodia', 'Camboya', 'Cambodja'),
(118, 'KI', 'KIR', 0, 'Kiribati', 'Kiribati', 'Kiribati'),
(119, 'KM', 'COM', 0, 'Comoros', 'Comoras', 'Comores'),
(120, 'KN', 'KNA', 0, 'Saint Kitts and Nevis', 'San Cristóbal y Nevis', 'Saint Kitts i Nevis'),
(121, 'KP', 'PRK', 0, 'Korea, Democratic People\'s Republic of', 'Corea del Norte', 'Corea del Nord'),
(122, 'KR', 'KOR', 0, 'Korea, Republic of', 'Corea del Sur', 'Corea del Sud'),
(123, 'KW', 'KWT', 0, 'Kuwait', 'Kuwait', 'Kuwait'),
(124, 'KY', 'CYM', 0, 'Cayman Islands', 'Islas Caimán', 'Caiman, illes'),
(125, 'KZ', 'KAZ', 0, 'Kazakhstan', 'Kazajstán', 'Kazakhstan'),
(126, 'LA', 'LAO', 0, 'Lao People\'s Democratic Republic', 'Laos', 'Laos'),
(127, 'LB', 'LBN', 0, 'Lebanon', 'Líbano', 'Líban'),
(128, 'LC', 'LCA', 0, 'Saint Lucia', 'Santa Lucía', 'Saint Lucia'),
(129, 'LI', 'LIE', 0, 'Liechtenstein', 'Liechtenstein', 'Liechtenstein'),
(130, 'LK', 'LKA', 0, 'Sri Lanka', 'Sri Lanka', 'Sri Lanka'),
(131, 'LR', 'LBR', 0, 'Liberia', 'Liberia', 'Libèria'),
(132, 'LS', 'LSO', 0, 'Lesotho', 'Lesotho', 'Lesotho'),
(133, 'LT', 'LTU', 1, 'Lithuania', 'Lituania', 'Lituània'),
(134, 'LU', 'LUX', 1, 'Luxembourg', 'Luxemburgo', 'Luxemburg'),
(135, 'LV', 'LVA', 1, 'Latvia', 'Letonia', 'Letònia'),
(136, 'LY', 'LBY', 0, 'Libyan Arab Jamahiriya', 'Libia', 'Líbia'),
(137, 'MA', 'MAR', 0, 'Morocco', 'Marruecos', 'Marroc'),
(138, 'MC', 'MCO', 0, 'Monaco', 'Mónaco', 'Mònaco'),
(139, 'MD', 'MDA', 0, 'Moldova, Republic of', 'Moldavia', 'Moldàvia'),
(140, 'ME', 'MNE', 0, 'Montenegro', 'ME', 'Montenegro'),
(141, 'MF', 'MAF', 0, 'Saint Martin', 'San Martín', 'Sant Martí'),
(142, 'MG', 'MDG', 0, 'Madagascar', 'Madagascar', 'Madagascar'),
(143, 'MH', 'MHL', 0, 'Marshall Islands', 'Islas Marshall', 'Marshall, illes'),
(144, 'MK', 'MKD', 0, 'Macedonia', 'ARY Macedonia', 'Macedònia'),
(145, 'ML', 'MLI', 0, 'Mali', 'Malí', 'Mali'),
(146, 'MM', 'MMR', 0, 'Myanmar', 'Myanmar', 'Myanmar'),
(147, 'MN', 'MNG', 0, 'Mongolia', 'Mongolia', 'Mongòlia'),
(148, 'MO', 'MAC', 0, 'Macao', 'Macao', 'Macau'),
(149, 'MP', 'MNP', 0, 'Northern Mariana Islands', 'Islas Marianas del Norte', 'Mariannes Septentrionals, illes'),
(150, 'MQ', 'MTQ', 0, 'Martinique', 'Martinica', 'Martinica'),
(151, 'MR', 'MRT', 0, 'Mauritania', 'Mauritania', 'Mauritània'),
(152, 'MS', 'MSR', 0, 'Montserrat', 'Montserrat', 'Montserrat'),
(153, 'MT', 'MLT', 1, 'Malta', 'Malta', 'Malta'),
(154, 'MU', 'MUS', 0, 'Mauritius', 'Mauricio', 'Maurici'),
(155, 'MV', 'MDV', 0, 'Maldives', 'Maldivas', 'Maldives'),
(156, 'MW', 'MWI', 0, 'Malawi', 'Malawi', 'Malawi'),
(157, 'MX', 'MEX', 0, 'Mexico', 'México', 'Mèxic'),
(158, 'MY', 'MYS', 0, 'Malaysia', 'Malasia', 'Malàisia'),
(159, 'MZ', 'MOZ', 0, 'Mozambique', 'Mozambique', 'Moçambic'),
(160, 'NA', 'NAM', 0, 'Namibia', 'Namibia', 'Namíbia'),
(161, 'NC', 'NCL', 0, 'New Caledonia', 'Nueva Caledonia', 'Nova Caledònia'),
(162, 'NE', 'NER', 0, 'Niger', 'Níger', 'Níger'),
(163, 'NF', 'NFK', 0, 'Norfolk Island', 'Isla Norfolk', 'Norfolk, illa'),
(164, 'NG', 'NGA', 0, 'Nigeria', 'Nigeria', 'Nigèria'),
(165, 'NI', 'NIC', 0, 'Nicaragua', 'Nicaragua', 'Nicaragua'),
(166, 'NL', 'NLD', 1, 'Netherlands', 'Países Bajos', 'Països Baixos'),
(167, 'NO', 'NOR', 0, 'Norway', 'Noruega', 'Noruega'),
(168, 'NP', 'NPL', 0, 'Nepal', 'Nepal', 'Nepal'),
(169, 'NR', 'NRU', 0, 'Nauru', 'Nauru', 'Nauru'),
(170, 'NU', 'NIU', 0, 'Niue', 'Niue', 'Niue'),
(171, 'NZ', 'NZL', 0, 'New Zealand', 'Nueva Zelanda', 'Nova Zelanda'),
(172, 'OM', 'OMN', 0, 'Oman', 'Omán', 'Oman'),
(173, 'PA', 'PAN', 0, 'Panama', 'Panamá', 'Panamà'),
(174, 'PE', 'PER', 0, 'Peru', 'Perú', 'Perú'),
(175, 'PF', 'PYF', 0, 'French Polynesia', 'Polinesia Francesa', 'Polinèsia Francesa'),
(176, 'PG', 'PNG', 0, 'Papua New Guinea', 'Papúa Nueva Guinea', 'Papua Nova Guinea'),
(177, 'PH', 'PHL', 0, 'Philippines', 'Filipinas', 'Filipines'),
(178, 'PK', 'PAK', 0, 'Pakistan', 'Pakistán', 'Pakistan'),
(179, 'PL', 'POL', 1, 'Poland', 'Polonia', 'Polònia'),
(180, 'PM', 'SPM', 0, 'Saint Pierre and Miquelon', 'San Pedro y Miquelón', 'Saint-Pierre i Miquelon'),
(181, 'PN', 'PCN', 0, 'Pitcairn', 'Islas Pitcairn', 'Pitcairn, illes'),
(182, 'PR', 'PRI', 0, 'Puerto Rico', 'Puerto Rico', 'Puerto Rico'),
(183, 'PS', 'PSE', 0, 'Palestinian Territory', 'Palestina', 'Palestina'),
(184, 'PT', 'PRT', 1, 'Portugal', 'Portugal', 'Portugal'),
(185, 'PW', 'PLW', 0, 'Palau', 'Palau', 'Palau'),
(186, 'PY', 'PRY', 0, 'Paraguay', 'Paraguay', 'Paraguai'),
(187, 'QA', 'QAT', 0, 'Qatar', 'Qatar', 'Qatar'),
(188, 'RE', 'REU', 0, 'Reunion', 'Reunión', 'Reunió, illa de la'),
(189, 'RO', 'ROU', 1, 'Romania', 'Rumania', 'Romania'),
(190, 'RS', 'SRB', 0, 'Serbia', 'RS', 'Sèrbia'),
(191, 'RU', 'RUS', 0, 'Russian Federation', 'Rusia', 'Rússia'),
(192, 'RW', 'RWA', 0, 'Rwanda', 'Ruanda', 'Rwanda'),
(193, 'SA', 'SAU', 0, 'Saudi Arabia', 'Arabia Saudí', 'Aràbia Saudita'),
(194, 'SB', 'SLB', 0, 'Solomon Islands', 'Islas Salomón', 'Salomó'),
(195, 'SC', 'SYC', 0, 'Seychelles', 'Seychelles', 'Seychelles'),
(196, 'SD', 'SDN', 0, 'Sudan', 'Sudán', 'Sudan'),
(197, 'SE', 'SWE', 1, 'Sweden', 'Suecia', 'Suècia'),
(198, 'SG', 'SGP', 0, 'Singapore', 'Singapur', 'Singapur'),
(199, 'SH', 'SHN', 0, 'Saint Helena', 'Santa Helena', 'Santa Helena'),
(200, 'SI', 'SVN', 1, 'Slovenia', 'Eslovenia', 'Eslovènia'),
(201, 'SJ', 'SJM', 0, 'Svalbard and Jan Mayen', 'Svalbard y Jan Mayen', 'Svalbard i Jan Mayen'),
(202, 'SK', 'SVK', 1, 'Slovakia', 'Eslovaquia', 'Eslovàquia'),
(203, 'SL', 'SLE', 0, 'Sierra Leone', 'Sierra Leona', 'Sierra Leone'),
(204, 'SM', 'SMR', 0, 'San Marino', 'San Marino', 'San Marino'),
(205, 'SN', 'SEN', 0, 'Senegal', 'Senegal', 'Senegal'),
(206, 'SO', 'SOM', 0, 'Somalia', 'Somalia', 'Somàlia'),
(207, 'SR', 'SUR', 0, 'Suriname', 'Surinam', 'Surinam'),
(208, 'SS', 'SSD', 0, 'South Sudan', 'Sudán del Sur', 'Sudan del Sud'),
(209, 'ST', 'STP', 0, 'Sao Tome and Principe', 'Santo Tomé y Príncipe', 'São Tomé i Príncipe'),
(210, 'SV', 'SLV', 0, 'El Salvador', 'El Salvador', 'Salvador, El'),
(211, 'SX', 'SXM', 0, 'Sint Maarten', 'Sint Maarten', 'Sint Maarten'),
(212, 'SY', 'SYR', 0, 'Syrian Arab Republic', 'Siria', 'Síria'),
(213, 'SZ', 'SWZ', 0, 'Swaziland', 'Suazilandia', 'Swazilàndia'),
(214, 'TC', 'TCA', 0, 'Turks and Caicos Islands', 'Islas Turcas y Caicos', 'Turks i Caicos, illes'),
(215, 'TD', 'TCD', 0, 'Chad', 'Chad', 'Txad'),
(216, 'TF', 'ATF', 0, 'French Southern Territories', 'Territorios Australes Franceses', 'Territoris Francesos del Sud'),
(217, 'TG', 'TGO', 0, 'Togo', 'Togo', 'Togo'),
(218, 'TH', 'THA', 0, 'Thailand', 'Tailandia', 'Tailàndia'),
(219, 'TJ', 'TJK', 0, 'Tajikistan', 'Tayikistán', 'Tadjikistan'),
(220, 'TK', 'TKL', 0, 'Tokelau', 'Tokelau', 'Tokelau'),
(221, 'TL', 'TLS', 0, 'Timor-Leste', 'Timor Oriental', 'Timor Oriental'),
(222, 'TM', 'TKM', 0, 'Turkmenistan', 'Turkmenistán', 'Turkmenistan'),
(223, 'TN', 'TUN', 0, 'Tunisia', 'Túnez', 'Tunísia'),
(224, 'TO', 'TON', 0, 'Tonga', 'Tonga', 'Tonga'),
(225, 'TR', 'TUR', 0, 'Turkey', 'Turquía', 'Turquia'),
(226, 'TT', 'TTO', 0, 'Trinidad and Tobago', 'Trinidad y Tobago', 'Trinitat i Tobago'),
(227, 'TV', 'TUV', 0, 'Tuvalu', 'Tuvalu', 'Tuvalu'),
(228, 'TW', 'TWN', 0, 'Taiwan', 'Taiwán', 'Taiwan'),
(229, 'TZ', 'TZA', 0, 'Tanzania, United Republic of', 'Tanzania', 'Tanzània'),
(230, 'UA', 'UKR', 0, 'Ukraine', 'Ucrania', 'Ucraïna'),
(231, 'UG', 'UGA', 0, 'Uganda', 'Uganda', 'Uganda'),
(232, 'UM', 'UMI', 0, 'United States Minor Outlying Islands', 'Islas ultramarinas de Estados Unidos', 'Illes Perifèriques Menors dels EUA'),
(233, 'US', 'USA', 0, 'United States', 'Estados Unidos', 'Estats Units (EUA)'),
(234, 'UY', 'URY', 0, 'Uruguay', 'Uruguay', 'Uruguai'),
(235, 'UZ', 'UZB', 0, 'Uzbekistan', 'Uzbekistán', 'Uzbekistan'),
(236, 'VA', 'VAT', 0, 'Holy See (Vatican City State)', 'Ciudad del Vaticano', 'Vaticà, Ciutat del'),
(237, 'VC', 'VCT', 0, 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas', 'Saint Vincent i les Grenadines'),
(238, 'VE', 'VEN', 0, 'Venezuela', 'Venezuela', 'Veneçuela'),
(239, 'VG', 'VGB', 0, 'Virgin Islands, British', 'Islas Vírgenes Británicas', 'Verges Britàniques, illes'),
(240, 'VI', 'VIR', 0, 'Virgin Islands, U.S.', 'Islas Vírgenes de los Estados Unidos', 'Verges Nord-americanes, illes'),
(241, 'VN', 'VNM', 0, 'Vietnam', 'Vietnam', 'Vietnam'),
(242, 'VU', 'VUT', 0, 'Vanuatu', 'Vanuatu', 'Vanuatu'),
(243, 'WF', 'WLF', 0, 'Wallis and Futuna', 'Wallis y Futuna', 'Wallis i Futuna'),
(244, 'WS', 'WSM', 0, 'Samoa', 'Samoa', 'Samoa'),
(245, 'YE', 'YEM', 0, 'Yemen', 'Yemen', 'Iemen'),
(246, 'YT', 'MYT', 0, 'Mayotte', 'Mayotte', 'Mayotte'),
(247, 'ZA', 'ZAF', 0, 'South Africa', 'Sudáfrica', 'Sud-àfrica'),
(248, 'ZM', 'ZMB', 0, 'Zambia', 'Zambia', 'Zàmbia'),
(249, 'ZW', 'ZWE', 0, 'Zimbabwe', 'Zimbabue', 'Zimbabwe');


ALTER TABLE `countries`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `eng` (`eng`),
  ADD UNIQUE KEY `spa` (`spa`),
  ADD UNIQUE KEY `cat` (`cat`),
  ADD UNIQUE KEY `iso2` (`iso2`),
  ADD UNIQUE KEY `iso3` (`iso3`),
  ADD KEY `is_eu` (`is_eu`);


ALTER TABLE `countries`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=250;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
